### ISSUE TITLE
Citra crash when using overlay

### ISSUE THREAD

**Issue by Lephikos** [Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator#9]
When using the overlay citra crashes. This happened multiple times in a row, sometimes right after the beginning of a quest (before even seeing the monster), sometimes after already fighting the monster for 15min.

I turned the debug-setting on and the log-file contains the following line when citra crashes: "ERROR - Update Position Error: 'NoneType' object has no attribute 'id'". Otherwise I turned everything except the hp and hp-percentage off.

I'm using the 1.1.3 version of the overlay and the following citra version: https://github.com/PabloMK7/citra (latest release: r608383e).
Game version is mh4u v1.1 (europe) and apart from the crashes the overlay works perfectly fine.

I don't know if that is something that is fixable tho, because it might just be an issue with the citra-version I'm using. I added the log-file from citra as file as attachment. All the "RPC_Server" and "HW.Memory" messages only appear while the overlay is running.

[citra_log.txt](https://github.com/user-attachments/files/18933869/citra_log.txt)

**Comment by Alexander-Lancellott** [comment]
Hi, thanks for taking the time to report this issue. I tried to replicate it using the same version of Citra you mentioned, but I was unsuccessful.

The error that appears in the `.log` file when enabling debug mode on the overlay is a generic message that happens when the overlay doesn’t detect any running game, so it’s not related to the issue you described.

By the way, remember to disable `debug` mode once you're done troubleshooting. This mode continuously writes to the `.log` file, and although the short-term impact is minimal, keeping it enabled for an extended period (such as years) could affect the lifespan of your storage drive.

That said, there could be several causes for the issue, so I suggest trying the following:

1. `Check the Firewall`: Make sure Citra is not blocked by [Windows Firewall rules](https://help.ovhcloud.com/csm/en-dedicated-servers-firewall-windows?id=kb_article_view&sysparm_article=KB0043216#step-2-enable-an-inbound-rule).

2. `Run as Administrator`: Try running both Citra and the overlay with administrator privileges.

3. `Reset settings and disable cheat/mods`: Certain settings or active cheats/mods in Citra might cause MH4U to behave unstably when running alongside the overlay. I recommend testing with Citra's default settings and disabling any cheats or mods you're using (except for FPS cheats, as those shouldn’t cause any conflicts).

4. `Use Nightly Citra`: If the issue persists after trying everything else, consider using the latest [Nightly version of Citra](https://archive.org/download/citra-emu_202403/citra-windows-msvc-20240303-0ff3440_nightly.zipl).

Let me know if any of these solutions work or if you need further assistance.

**Comment by Alexander-Lancellott** [comment]
Hi again,

I’ve been looking into the `HW.Memory` error that appeared in Citra's log file. The issue was caused by the pointers read by the Overlay, which were pointing to addresses below `0x100000`, triggering those errors when trying to read them.

This should now be fixed in [version 1.1.4 of the Overlay](https://github.com/Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator/releases/tag/v1.1.4), which I just released a few minutes ago.

However, I can't guarantee that this will completely resolve Citra's crashes when using the Overlay, as I wasn't able to reproduce them during my tests.

Please let me know if everything works fine with this latest version.

**Comment by Lephikos** [comment]
Hey,

I have already been able to test some of the points you suggested today (suggestions 1-3), but unfortunately without success. However, I have not yet been able to test another Citra version (also because I use this specific Citra version in order to be able to use the Pretendo network with Citra).
I will test the whole thing again with the new version and report back later this week with the results.

In any case, thank you very much for your help. The overlay is really useful and well designed!

**Comment by Lephikos** [comment]
Hello again,

I had some time today to test the new version. Unfortunately, I still get crashes. But apart from a few exceptions, the HW.Memory errors no longer occur.

I also tried to set the overlay refresh rate to one second (instead of 0.5 as default), but that didn't help either and somehow resulted in an even faster crash.

I have attached two log files from citra (this time with "always flush" enabled and without any filtering of the log levels), which contain everything from start to crash. (Both contain a message about a failed assertion near the end. But I don't know if that's a result of the crash or the cause of it)
For the sake of completeness, I have also taken a screenshot of the Traceback of the Overlay displayed in the console after a crash, even if this looks more like a problem with citra than with the Overlay.

![Image](https://github.com/user-attachments/assets/ced20701-be5b-4f38-bd52-52e802a21402)

[citra_log.txt](https://github.com/user-attachments/files/18971672/citra_log.txt)

[citra_log.txt.old.txt](https://github.com/user-attachments/files/18971674/citra_log.txt.old.txt)

**Comment by Alexander-Lancellott** [comment]
Just to confirm, when you reset Citra's settings to default, did you rename the Citra folder ? usually located at:

`C:\Users\YourUserName\AppData\Roaming\Citra`

If you didn't, I recommend doing so to force a clean reconfiguration. It's important not to delete the folder — just rename it, as it contains your save files.

After renaming it, restart Citra. This will create a new Citra folder in Roaming with the default settings. Then, copy only your save files to the new folder without adding anything else.

Finally, test the overlay again in case you hadn't followed this process before.

If you've already tried this and it still doesn't work, I'm sorry I can't be of more help — this is beyond what I can do.

**Comment by Lephikos** [comment]
Hey,

I had a bit of time at the weekend to test again. Unfortunately Citra still crashes a lot (even with no 3rd party program of any kind running). After downloading the source code and rebuilding the whole thing I was able to run Citra via Visual Studio. It seems like it is some kind of heap allocation and permission error which causes Citra to crash. So it is definitely Citra's fault with the specific release I am using.

Thank you for all the helpful tips and the time you dedicated to assisting me. I believe this issue can now be considered closed, as it turns out it wasn’t related to the overlay after all.
